---
- name: Copy Zabbix Agent
  copy:
     src: zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb 
     dest: /tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb


- name: Download Zabbix Agent
  get_url: url=http://repo.zabbix.com/zabbix/{{zabbix_release}}/debian/pool/main/z/zabbix/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb
           dest=/tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb

- name: Install Zabbix Agent
  apt:
     deb: /tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb
     update_cache: yes

- name: Remove downloaded files
  file:
     state: absent
     path: /tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb
 
- name: Configure Zabbix
  template: 
        src: zabbix_agentd.j2 
        dest: /etc/zabbix/zabbix_agentd.conf
  notify:
        - restart zabbix-agent

- name: Install requirements 1
  apt:
        name: python-pip
        
- name: Install requirements 2
  pip:
        name: zabbix-api

- name: Add on Zabbix Server
  zabbix_host:
        server_url: "http://{{zabbix_server_address}}/zabbix"
        login_user:  "{{zabbix_server_user}}"
        login_password: "{{zabbix_server_pass}}"
        host_name: "{{ansible_facts['nodename']}}"
        host_groups: "{{zabbix_host_groups}}"
        link_templates: "{{zabbix_agent_templates}}"
        interfaces:
                - type: 1
                  main: 1
                  useip: 1
                  ip: "{{ansible_facts.default_ipv4.address}}"
        state: present
