---

- name: Download Zabbix
  get_url: url=http://repo.zabbix.com/zabbix/{{zabbix_release}}/debian/pool/main/z/zabbix/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb
           dest=/tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb

- name: Install Zabbix
  apt:
     deb: /tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb
     update_cache: yes

- name: Remove downloaded files
  file:
     state: absent
     path: /tmp/zabbix-agent_{{zabbix_version}}+{{debian_version}}_amd64.deb
 
- name: Configure Zabbix
  template: 
        src: zabbix_agentd.j2 
        dest: /etc/zabbix/zabbix_agentd.conf

