---

- name: Install the correct OS repository
  include: "Debian.yml"
  when:
        - zabbix_agent_os_family == "Debian"

- name: Install the correct OS repository
  include: "Windows.yml"
  when:
        - zabbix_agent_os_family == "Windows"
 
- name: "set default zabbix_agent_ip"
  set_fact:
          zabbix_agent_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4'].address}}"
  when:
        - zabbix_agent_ip is not defined
        - "'ansible_default_ipv4' in hostvars[inventory_hostname]"

- name: "set default zabbix_agent_ip for windows"
  set_fact:
          zabbix_agent_ip: "{{hostvars[inventory_hostname]['ansible_ip_addresses'] | first}}"
  when:
       - zabbix_agent_ip is not defined
       - "'ansible_ip_addresses' in hostvars[inventory_hostname]"

- name: Add on Zabbix Server
  zabbix_host:
        server_url: "http://{{zabbix_server_address}}/zabbix"
        login_user:  "{{zabbix_server_user}}"
        login_password: "{{zabbix_server_pass}}"
        host_name: "{{ansible_facts['nodename']}}"
        host_groups: "{{zabbix_host_groups}}"
        link_templates: "{{zabbix_link_templates}}"
        interfaces:
                - type: 1
                  main: 1
                  useip: 1
                  ip: "{{zabbix_agent_ip}}"
        state: present
  delegate_to: localhost
  become: no
