---

- name: "set variables for windows environment"
  set_fact:
          zabbix_win_package: zabbix_agents-4.2.1-win-amd64.zip
          zabbix_win_exe_path: '{{zabbix_win_install_dir}}\bin\zabbix_agentd.exe'
          zabbix_win_install_dir: 'C:\'

- name: "Check zabbix agent stats"
  win_stat:
     path: '{{zabbix_win_exe_path}}'
  register: zabbix_agent_file_info

- name: "check zabbix package stats"
  win_stat:
     path: '{{zabbix_win_install_dir}}\{{zabbix_win_package}}'
  register: package_file_info

- name: Copy Zabbix Agent
  win_copy:
     src: '{{zabbix_win_package}}'
     dest: '{{zabbix_win_install_dir}}'
  when:
      - not package_file_info.stat.exists
 
- name: "unzip zabbix agent package"
  win_unzip:
      src: '{{zabbix_win_install_dir}}\{{zabbix_win_package}}'
      dest: '{{zabbix_win_install_dir}}\zabbix'
